# Generated by Django 4.2.28 on 2026-07-12 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(db_index=True, help_text='Unique driving license number', max_length=30, unique=True)),
                ('license_category', models.CharField(choices=[('Class A', 'Class A — Heavy Vehicles'), ('Class B', 'Class B — Medium Vehicles'), ('Class C', 'Class C — Light Vehicles'), ('Class D', 'Class D — Passenger')], max_length=10)),
                ('license_expiry', models.DateField(help_text='Date on which the driving license expires')),
                ('contact_number', models.CharField(max_length=20)),
                ('safety_score', models.FloatField(default=100.0, help_text='Safety score on a 0–100 scale. Updated by Safety Officers.', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty'), ('Suspended', 'Suspended')], db_index=True, default='Available', max_length=15)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-safety_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, help_text='Unique vehicle registration plate (e.g. MH-12-AB-1234)', max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('Semi Trailer', 'Semi Trailer'), ('Pickup', 'Pickup'), ('Car', 'Car')], max_length=20)),
                ('max_load_capacity', models.FloatField(help_text='Maximum cargo weight in kilograms', validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer', models.FloatField(default=0.0, help_text='Current odometer reading in kilometres', validators=[django.core.validators.MinValueValidator(0)])),
                ('acquisition_cost', models.FloatField(help_text='Purchase price in local currency', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], db_index=True, default='Available', max_length=15)),
                ('region', models.CharField(db_index=True, help_text='Operational region (e.g. North, South, East)', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
